version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/react-app
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - user-codes:/app/codes    
      - /var/run/docker.sock:/var/run/docker.sock
  code-runner:
    image: code-runner
    build: ./backend/coderun
    depends_on:
      - backend
    volumes:
      - user-codes:/app
volumes:
  user-codes:
    external: true
    
