FROM ubuntu

RUN apt-get update -y
RUN apt install nodejs -y
RUN apt-get -y upgrade
RUN apt-get install python3 -y
RUN apt-get update -y
RUN apt-get install g++ -y
RUN apt-get update -y
RUN apt-get install time -y
RUN mkdir app

WORKDIR /app